export const cars = [
  {
    id: 1,
    image: "http://localhost:3000/images/car4.jpg",
    description: "Toyota Cross",
    owner: "Carlos Perez",
    year: "2023",
    mileage: "74900",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },
  {
    id: 2,
    image: "http://localhost:3000/images/car2.jpg",
    description: "Kia Seltos",
    owner: "Juan Gutierrez",
    year: "2020",
    mileage: "110500",
    fuel: "Gasolina",
    gearbox: "Automatica",
    price: "789",
  },

  {
    id: 3,
    image: "http://localhost:3000/images/car3.jpg",
    description: "Hyundia Tucson",
    owner: "Pedro Gonzalez",
    year: "2024",
    mileage: "54600",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },

  {
    id: 4,
    image: "http://localhost:3000/images/car3.jpg",
    description: "Hyundia Tucson",
    owner: "Pedro Rocha",
    year: "2024",
    mileage: "54600",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },
  {
    id: 5,
    image: "http://localhost:3000/images/car4.jpg",
    description: "Toyota Cross",
    owner: "Carlos Gonzalez",
    year: "2023",
    mileage: "74900",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },
  {
    id: 6,
    image: "http://localhost:3000/images/car2.jpg",
    description: "Kia Seltos",
    owner: "Juan Perez",
    year: "2020",
    mileage: "110500",
    fuel: "Gasolina",
    gearbox: "Automatica",
    price: "789",
  },

  {
    id: 7,
    image: "http://localhost:3000/images/car3.jpg",
    description: "Hyundia Tucson",
    owner: "Pedro Cruz",
    year: "2024",
    mileage: "54600",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },

  {
    id: 8,
    image: "http://localhost:3000/images/car3.jpg",
    description: "Hyundia Tucson",
    owner: "Pedro Gonzalez",
    year: "2024",
    mileage: "54600",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },

  {
    id: 9,
    image: "http://localhost:3000/images/car3.jpg",
    description: "Hyundia Tucson",
    owner: "Pedro Gonzalez",
    year: "2024",
    mileage: "54600",
    fuel: "Diesel",
    gearbox: "Automatica",
    price: "789",
  },
];
